### ISSUE TITLE
When I try the demo it says user forms does not exist

### ISSUE THREAD

**Issue by arhoy** [seabeams/gatsby-starter-auth-aws-amplify#2]
I tried your demo,
it is not working
![user pool dne](https://user-images.githubusercontent.com/10405245/77746763-0f1c6580-6fe3-11ea-9dde-2954e6ffd764.PNG)

**Comment by seabeams** [comment]
Sorry, I removed the app from my AWS account because I had so many users signing up and didn't want to risk racking up a bill.

Set up an AWS free tier account and try it out. Let me know if you have any other issues.

I'll leave this open temporarily.
