### ISSUE TITLE
Error: Cannot create as TypeComposer the following value: Date

### ISSUE THREAD

**Issue by kj96** [seabeams/gatsby-starter-auth-aws-amplify#6]
I started a new project and completed Amplify configuration.
Then on executing `gatsby develop` gives `Error: Cannot create as TypeComposer the following value: Date`

![image](https://user-images.githubusercontent.com/17710098/88171104-66061480-cc3c-11ea-8b67-8f0a5cccd3b8.png)

**Comment by kj96** [comment]
After checking similar issue https://github.com/gatsbyjs/gatsby/issues/13278
 
I checked my GraphSQL verision:
![image](https://user-images.githubusercontent.com/17710098/88171549-23910780-cc3d-11ea-9261-4fd25f45d21a.png)

So I deleted `node_modules` and `package-lock.json` 
And reinstalled all dependencies from `package.json`

And it Worked!

**Comment by seabeams** [comment]
Thanks for sharing and glad you solved it!
